# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  gatling:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "temurin"
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: run-gatling
    - uses: liatrio/run-gatling@v1.2.0
      with:
        # Java Version to use
        # Default: '17'
        javaVersion: '17'
    
        # Java Distribution to use
        # Default: 'microsoft'
        javaDistribution: 'temurin'
    
        # Path to the Gatling Test Suite's pom.xml file
        # Default: './test'
        pomPath: './'
    
        # Class of the simulation to run ('myPackage.MySimulationClass')
        # Default: ''
        # (Optionnal)
        # Note: If the Test Suite contains more than one simulation,
        #       you may want to configure the Maven plugin to run 
        #       multiple simulations. Otherwise, you will have to fill this
        #       parameter with the specific simulation to execute.
        simulationClass: ''
            

