# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  gatling-test:
    # Use the latest Ubuntu runner environment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code to the runner
      - name: Checkout code
        uses: actions/checkout@v4
        # No additional parameters required for checkout

      # Step 2: Set up a specific version of Java (required by Gatling)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17' 
          distribution: 'temurin'
          cache: maven

      # Step 3: Cache dependencies to speed up subsequent runs
      - name: Cache Gatling dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.ivy2/cache
            ~/.sbt/boot
            ~/.coursier
          key: ${{ runner.os }}-gatling-${{ hashFiles('**/pom.xml', '**/build.sbt') }}
          # Use restore-keys to find a cache in case of a cache miss
          restore-keys: |
            ${{ runner.os }}-gatling-

      # Step 4: Run the Gatling test using your build tool's specific command
      - name: Run Gatling test
        run: mvn gatling:test

      # Step 5: Upload Gatling reports as artifacts for review
      - name: Upload Gatling reports
        uses: actions/upload-artifact@v4
        with:
          name: gatling-reports
          # Ensure this path matches where your Gatling reports are generated
          path: |
            target/gatling/**

